/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mdunbar' at '2/15/17 8:15 AM' with Gradle 2.12
 *
 * @author mdunbar, @date 2/15/17 8:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
