/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'mdunbar' at '2/15/17 8:15 AM' with Gradle 2.12
 *
 * @author mdunbar, @date 2/15/17 8:15 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
